CREATE TABLE USUARIO(
	ID_USU INT NOT NULL PRIMARY KEY,
  	USER_NAME VARCHAR(50) NOT NULL,
	USER_PASSWORD VARCHAR(200) NOT NULL,
	REAL_NAME VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL
);

CREATE TABLE QUADRO(
	ID_QUA INT NOT NULL PRIMARY KEY,
  	NAME_QUA VARCHAR(50) NOT NULL,
	ID_USU INT NOT NULL REFERENCES USUARIO(ID_USU)
);

CREATE TABLE COLUNA(
	ID_COL INT NOT NULL PRIMARY KEY,
  	NAME_COL VARCHAR(50) NOT NULL,
	ID_QUA INT NOT NULL REFERENCES QUADRO(ID_QUA)
);

CREATE TABLE ATIVIDADE(
	ID_ATI INT NOT NULL PRIMARY KEY,
  	TITLE VARCHAR(50) NOT NULL,
	ATI_TEXT VARCHAR(350),
	PRAZO DATE,
	ID_QUA INT NOT NULL REFERENCES QUADRO(ID_QUA),
    ID_COL INT NOT NULL REFERENCES COLUNA(ID_COL),
    ID_USU INT NOT NULL REFERENCES USUARIO(ID_USU)
);

CREATE TABLE ATI_LINK(
	ID_LIN INT NOT NULL PRIMARY KEY,
	TEXT_LINK VARCHAR(500),
	ID_ATI INT NOT NULL REFERENCES ATIVIDADE(ID_ATI)
);

CREATE TABLE COMENTA(
	ID_COMENT INT NOT NULL PRIMARY KEY,
	CONTEUDO VARCHAR(250),
	ID_USER INT NOT NULL REFERENCES USUARIO(ID_USU),
	ID_ATI INT NOT NULL REFERENCES ATIVIDADE(ID_ATI)
    STATUS BOOLEAN NOT NULL;    
);

CREATE TABLE CHECKBOX(
	ID_CHECKBOX INT NOT NULL PRIMARY KEY,
	TEXT_LINK VARCHAR(500),
	ID_ATI INT NOT NULL REFERENCES ATIVIDADE(ID_ATI)
);
